server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EF302/myspringcloud.git
          search-paths: config
          username: EF302
          password: Lwl15284969061!
      label: master
eureka:
  client:
    service-url:
      #注册中⼼的访问地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    #是否将当前服务的IP注册到Eureka Server
    prefer-ip-address: true
